// JS <-> Python derive parity (PRD 00065 / the seam PRD 00068 deferred).
//
// The whole point of the shared-fixture risk mitigation: the SAME data.json in
// yields the SAME derived view-model out on both the JS and the Python side.
//
//   - data.json + epics.json are the canonical fixtures, generated by the
//     Python contract's `write_outputs(_enriched_portfolio())` (see
//     tests/tools/postup/domain/test_derive.py) so they are byte-parity with
//     what the Python side actually reads.
//   - py_viewmodel_enriched.json is the Python `load_view_model(...)` output on
//     those fixtures, serialised to JSON — the expected derived values.
//
// This test computes the JS view-model projection over the SAME fixture and
// asserts equality field-for-field. A divergence on either side (a fixture
// edit, a derive change) fails here — exactly the failure the PRD wants surfaced.
import { describe, it, expect } from 'vitest';
import data from '../fixtures/data.json';
import epics from '../fixtures/epics.json';
import expected from '../fixtures/py_viewmodel_enriched.json';
import { viewModel } from './viewmodel.js';

describe('JS/Python derive parity', () => {
	const js = viewModel(data, epics);

	it('flags enriched state identically', () => {
		expect(js.needs_collect).toBe(expected.needs_collect);
		expect(js.enriched).toBe(expected.enriched);
		expect(js.generated_at).toBe(expected.generated_at);
		expect(js.summary).toBe(expected.summary);
	});

	it('produces the same per-repo summaries', () => {
		expect(js.repos).toEqual(expected.repos);
	});

	it('produces the same ranked attention queue', () => {
		expect(js.attention).toEqual(expected.attention);
	});

	it('produces the same mechanical + judgment todo set', () => {
		expect(js.todos).toEqual(expected.todos);
	});

	it('produces the same portfolio-level errors', () => {
		expect(js.errors).toEqual(expected.errors);
	});

	it('matches the full serialised Python view-model (since_last excluded — no prev fixture)', () => {
		const { since_last: _pySince, ...pyRest } = expected;
		const { since_last: _jsSince, ...jsRest } = js;
		expect(jsRest).toEqual(pyRest);
	});
});
