from typing import Any

def parse_file(path: str) -> dict[str, Any]: ...
def load_all(directory: str, extensions: list[str] | None = None) -> list[dict[str, Any]]: ...
def search(directory: str, query: str, extensions: list[str] | None = None) -> list[dict[str, Any]]: ...
