from typing import Any

def parse_file(path: str) -> dict[str, Any]: ...
def load_all(directory: str, extensions: list[str] | None = None) -> list[dict[str, Any]]: ...
def load_filtered(
    directory: str,
    extensions: list[str] | None = None,
    metadata_eq: dict[str, Any] | None = None,
    cache_path: str | None = None,
) -> list[dict[str, Any]]: ...
def search(directory: str, query: str, extensions: list[str] | None = None) -> list[dict[str, Any]]: ...
def refresh_cache(directory: str, cache_path: str, extensions: list[str] | None = None) -> str: ...
