"""Textual snapshot tests for :class:`postup.adapters.tui.app.PostupApp`.

Per AGENTS.md, snapshot tests carry ``@pytest.mark.snapshot`` and only run on the
canonical env (Linux + Python 3.12); everywhere else the top-level conftest
auto-skips them, so locally these SKIP (not fail). Baselines are generated by the
``update-snapshots`` GitHub workflow — never hand-blessed and never regenerated
with ``--snapshot-update`` locally.

The view-models are built directly (the app computes nothing), so the SVG output
is fully deterministic: no clock, no spinner, no animation to normalize.
"""

from __future__ import annotations

import pytest
from postup.domain.derive import AttentionItem, RepoSummary, SinceLast, Todo, ViewModel

TERMINAL_SIZES = [
    pytest.param((80, 24), id="80x24"),
    pytest.param((120, 40), id="120x40"),
]


def _enriched_vm() -> ViewModel:
    """A fully-populated, enriched standup (the happy-path layout)."""
    return ViewModel(
        needs_collect=False,
        enriched=True,
        generated_at="2026-09-28T10:00:00+00:00",
        summary="Two repos moved this week; gems shipped the collector, docs is quiet.",
        attention=(
            AttentionItem(repo="buvis/gems", urgency="now", headline="1 failing CI workflow(s)", kind="ci"),
            AttentionItem(repo="buvis/gems", urgency="now", headline="1 open security alert(s)", kind="security"),
            AttentionItem(repo="buvis/gems", urgency="soon", headline="2 open PR(s) awaiting attention", kind="review"),
            AttentionItem(
                repo="other/thing", urgency="soon", headline="review requested: #77 fix", kind="external-review"
            ),
        ),
        todos=(
            Todo(
                repo="buvis/gems", action="fix failing CI", why="default branch red", kind="mechanical", urgency="now"
            ),
            Todo(
                repo="buvis/gems", action="cut a release", why="3 unreleased commits", kind="mechanical", urgency="soon"
            ),
            Todo(
                repo="buvis/gems", action="Resume the parked PRD", why="dirty for days", kind="judgment", urgency="now"
            ),
        ),
        repos=(
            RepoSummary(
                repo="buvis/docs", commits=3, open_prs=0, open_issues=0, failing_ci=0, alerts=0, unreleased=0, dirty=0
            ),
            RepoSummary(
                repo="buvis/gems", commits=42, open_prs=2, open_issues=1, failing_ci=1, alerts=1, unreleased=3, dirty=4
            ),
        ),
        since_last=SinceLast(has_prev=True, commits=5, open_prs=1, open_issues=0, alerts=1, failing_ci=1),
    )


def _degraded_vm() -> ViewModel:
    """A standup with per-repo and portfolio-level errors (the errors[] state)."""
    return ViewModel(
        needs_collect=False,
        enriched=False,
        generated_at="2026-09-28T10:00:00+00:00",
        attention=(AttentionItem(repo="buvis/gems", urgency="now", headline="1 failing CI workflow(s)", kind="ci"),),
        todos=(
            Todo(
                repo="buvis/gems", action="fix failing CI", why="default branch red", kind="mechanical", urgency="now"
            ),
        ),
        repos=(
            RepoSummary(
                repo="buvis/gems",
                commits=0,
                open_prs=0,
                open_issues=0,
                failing_ci=1,
                alerts=0,
                unreleased=0,
                dirty=0,
                errors=("meta: gh unauthenticated", "commits: git fetch failed"),
            ),
        ),
        since_last=SinceLast(has_prev=False),
        errors=("external PRs: gh rate limited",),
    )


def _not_enriched_vm() -> ViewModel:
    """A collected-but-not-enriched standup (the deterministic subset)."""
    return ViewModel(
        needs_collect=False,
        enriched=False,
        generated_at="2026-09-28T10:00:00+00:00",
        attention=(
            AttentionItem(repo="buvis/gems", urgency="soon", headline="1 open PR(s) awaiting attention", kind="review"),
        ),
        todos=(
            Todo(
                repo="buvis/gems", action="cut a release", why="3 unreleased commits", kind="mechanical", urgency="soon"
            ),
        ),
        repos=(
            RepoSummary(
                repo="buvis/gems", commits=12, open_prs=1, open_issues=0, failing_ci=0, alerts=0, unreleased=3, dirty=0
            ),
        ),
        since_last=SinceLast(has_prev=False),
    )


class TestPostupTuiSnapshots:
    @pytest.mark.snapshot
    @pytest.mark.postup
    @pytest.mark.parametrize("terminal_size", TERMINAL_SIZES)
    def test_main_layout_enriched(self, snap_compare, terminal_size):
        from postup.adapters.tui.app import PostupApp

        assert snap_compare(PostupApp(_enriched_vm()), terminal_size=terminal_size)

    @pytest.mark.snapshot
    @pytest.mark.postup
    def test_degraded_layout_with_errors(self, snap_compare):
        from postup.adapters.tui.app import PostupApp

        assert snap_compare(PostupApp(_degraded_vm()), terminal_size=(120, 40))

    @pytest.mark.snapshot
    @pytest.mark.postup
    def test_not_enriched_layout(self, snap_compare):
        from postup.adapters.tui.app import PostupApp

        assert snap_compare(PostupApp(_not_enriched_vm()), terminal_size=(120, 40))
